version: '3.7'

services:
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./django-template/static:/static
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"

  web:
    restart: always
    build:
      context: ./django-template
      args:
        - REQUIREMENT_TXT=$REQUIREMENT_TXT
    volumes:
      - ./django-template:/django-app/
    ports:
      - "3033:3033"
    command: uwsgi uwsgi.ini --socket :3033
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - db

  db:
    restart: always
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: django
      MYSQL_ROOT_PASSWORD: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: mysqlvolume
        target: /var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d

  adminer:
    restart: always
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mysqlvolume:
    driver: local


